-- Baseline migration intentionally left empty.
-- The users table already exists in databases created before migration history was restored.
-- Later migrations add the newer authentication columns safely.
